<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 *
 * Class NSIconPicker
 *
 * For iconpicker shortcode param.
 */
class NSIconPicker {
	/**
	 * @var array - save current param data array from vc_map
	 */
	protected $settings;
	/**
	 * @var string - save a current field value
	 */
	protected $value;
	/**
	 * @var array - optional, can be used as self source from self array., you can pass it also with filter see
	 *     NSIconPicker::setDefaults
	 */
	protected $source = array();

	/**
	 * @param $settings - param field data array
	 * @param $value    - param field value
	 */
	public function __construct( $settings, $value ) {
		$this->settings = $settings;
		$this->setDefaults();

		$this->value = $value; // param field value
	}

	/**
	 * Set default function will extend current settings with defaults
	 */
	protected function setDefaults() {
		if ( ! isset( $this->settings['settings'], $this->settings['settings']['type'] ) ) {
			$this->settings['settings']['type'] = 'fontawesome'; // Default type for icons
		}

		// More about this you can read in http://codeb.it/fonticonpicker/
		if ( ! isset( $this->settings['settings'], $this->settings['settings']['hasSearch'] ) ) {
			// Whether or not to show the search bar.
			$this->settings['settings']['hasSearch'] = true;
		}
		if ( ! isset( $this->settings['settings'], $this->settings['settings']['emptyIcon'] ) ) {
			// Whether or not empty icon should be shown on the icon picker
			$this->settings['settings']['emptyIcon'] = true;
		}
		if ( ! isset( $this->settings['settings'], $this->settings['settings']['allCategoryText'] ) ) {
			// If categorized then use this option
			$this->settings['settings']['allCategoryText'] = __( 'From all categories', 'js_composer' );
		}
		if ( ! isset( $this->settings['settings'], $this->settings['settings']['unCategorizedText'] ) ) {
			// If categorized then use this option
			$this->settings['settings']['unCategorizedText'] = __( 'Uncategorized', 'js_composer' );
		}

		/**
		 * Source for icons
		 */
		if ( isset( $this->settings['settings'], $this->settings['settings']['source'] ) ) {
			$this->source = $this->settings['settings']['source'];
			unset( $this->settings['settings']['source'] ); // We don't need this on frontend.(js)
		}
	}

	/**
	 * Render edit form field type 'iconpicker' with selected settings and provided value.
	 */
	public function render() {

		$name    = isset( $this->settings['param_name'] ) ? $this->settings['param_name'] : '';
		$setting = ( isset( $this->settings['settings'] ) && ! empty( $this->settings['settings'] ) ) ? $this->settings['settings'] : false;
		$type    = esc_attr( $this->settings['settings']['type'] );

		// use the filter vc_iconpicker-type-{your_type} from VC to get the icons.
		$arr = apply_filters( 'vc_iconpicker-type-' . $type, $this->source );

		// If there's no icons, try get from our own functions.
		if ( empty( $arr ) && function_exists( 'ns_iconpicker_' . $type ) ) {
			$arr = call_user_func( 'ns_iconpicker_' . $type );
		}

		if ( $setting && isset( $setting['emptyIcon'] ) && true === $setting['emptyIcon'] ) {
			array_unshift( $arr, array() );
		}

		$output = '<div class="ns-iconpicker-wrapper"><select name="' . esc_attr( $name ) . '" class="ns-iconpicker"' . ( $setting ? ' data-settings="' . esc_attr( json_encode( $setting ) ) . '" ' : '' ) . '>';
		if ( ! empty( $arr ) ) {
			foreach ( $arr as $group => $icons ) {
				if ( ! is_array( $icons ) || ! is_array( current( $icons ) ) ) {
					$class_key = key( $icons );
					$output    .= '<option value="' . esc_attr( $class_key ) . '" ' . selected( $class_key,
							$this->value, false ) . '>' . esc_html( current( $icons ) ) . '</option>' . "\n";
				} else {
					$output .= '<optgroup label="' . esc_attr( $group ) . '">' . "\n";
					foreach ( $icons as $key => $label ) {
						$class_key = key( $label );
						$output    .= '<option value="' . esc_attr( $class_key ) . '" ' . selected( $class_key,
								$this->value, false ) . '>' . esc_html( current( $label ) ) . '</option>' . "\n";
					}
					$output .= '</optgroup>' . "\n";
				}
			}
		}
		$output .= '</select></div>';

		// $output .= '<input type="hidden" value="' . esc_attr( $this->value ) . '" />';

		return $output;
	}
}

/**
 * IconPicker shortcode param.
 *
 * @param $settings
 * @param $value
 *
 * @return string - html string.
 */
if ( ! function_exists( 'ns_iconpicker_param' ) ) :
	function ns_iconpicker_param( $settings, $value ) {

		$icon_picker = new NSIconPicker( $settings, $value );

		return $icon_picker->render();
	}

	ns_add_shortcode_param( 'iconpicker', 'ns_iconpicker_param' );

endif;

if ( ! function_exists( 'ns_iconpicker_fontawesome' ) ) :
	/**
	 * Fontawesome icons from FontAwesome :)
	 *
	 * @return array - of icons for iconpicker, can be categorized, or not.
	 */
	function ns_iconpicker_fontawesome() {
		// Categorized icons ( you can also output simple array ( key=> value ), where key = icon class, value = icon readable name ).

		$fontawesome_icons = array(
			'New in 4.6'            => array(
				array( 'fa-instagram' => 'Instagram' ),
				array( 'fa-gitlab' => 'GitLab' ),
				array( 'fa-wpbeginner' => 'WPBeginner' ),
				array( 'fa-wpforms' => 'WPForms' ),
				array( 'fa-envira' => 'Envira Gallery(leaf)' ),
				array( 'fa-universal-access' => 'Universal Access' ),
				array( 'fa-wheelchair-alt' => 'Wheelchair Alt' ),
				array( 'fa-question-circle-o' => 'Question Circle Outlined' ),
				array( 'fa-blind' => 'Blind' ),
				array( 'fa-audio-description' => 'Audio Description' ),
				array( 'fa-volume-control-phone' => 'Volume Control Phone' ),
				array( 'fa-braille' => 'Braille' ),
				array( 'fa-assistive-listening-systems' => 'Assistive Listening Systems' ),
				array( 'fa-american-sign-language-interpreting' => 'American Sign Language Interpreting(asl-interpreting)' ),
				array( 'fa-deaf' => 'Deaf(deafness, hard-of-hearing)' ),
				array( 'fa-glide' => 'Glide' ),
				array( 'fa-glide-g' => 'Glide G' ),
				array( 'fa-sign-language' => 'Sign Language(signing)' ),
				array( 'fa-low-vision' => 'Low Vision' ),
				array( 'fa-viadeo' => 'Viadeo' ),
				array( 'fa-viadeo-square' => 'Viadeo Square' ),
				array( 'fa-snapchat' => 'Snapchat' ),
				array( 'fa-snapchat-ghost' => 'Snapchat Ghost' ),
				array( 'fa-snapchat-square' => 'Snapchat Square' ),
				array( 'fa-pied-piper' => 'Pied Piper Logo' ),
				array( 'fa-first-order' => 'First Order' ),
				array( 'fa-yoast' => 'Yoast' ),
				array( 'fa-themeisle' => 'ThemeIsle' ),
				array( 'fa-google-plus-official' => 'Google Plus Official(google-plus-circle)' ),
				array( 'fa-font-awesome' => 'Font Awesome(fa)' ),
			),
			'Web Application Icons' => array(
				array( 'fa-glass' => 'Glass(martini, drink, bar, alcohol, liquor)' ),
				array( 'fa-music' => 'Music(note, sound)' ),
				array( 'fa-search' => 'Search(magnify, zoom, enlarge, bigger)' ),
				array( 'fa-envelope-o' => 'Envelope Outlined(email, support, e-mail, letter, mail, notification)' ),
				array( 'fa-heart' => 'Heart(love, like, favorite)' ),
				array( 'fa-star' => 'Star(award, achievement, night, rating, score, favorite)' ),
				array( 'fa-star-o' => 'Star Outlined(award, achievement, night, rating, score, favorite)' ),
				array( 'fa-user' => 'User(person, man, head, profile)' ),
				array( 'fa-film' => 'Film(movie)' ),
				array( 'fa-check' => 'Check(checkmark, done, todo, agree, accept, confirm, tick, ok)' ),
				array( 'fa-times' => 'Times(close, exit, x, cross)(remove, close)' ),
				array( 'fa-search-plus' => 'Search Plus(magnify, zoom, enlarge, bigger)' ),
				array( 'fa-search-minus' => 'Search Minus(magnify, minify, zoom, smaller)' ),
				array( 'fa-power-off' => 'Power Off(on)' ),
				array( 'fa-signal' => 'signal(graph, bars)' ),
				array( 'fa-cog' => 'cog(settings)(gear)' ),
				array( 'fa-trash-o' => 'Trash Outlined(garbage, delete, remove, trash, hide)' ),
				array( 'fa-home' => 'home(main, house)' ),
				array( 'fa-clock-o' => 'Clock Outlined(watch, timer, late, timestamp)' ),
				array( 'fa-road' => 'road(street)' ),
				array( 'fa-download' => 'Download(import)' ),
				array( 'fa-inbox' => 'inbox' ),
				array( 'fa-refresh' => 'refresh(reload, sync)' ),
				array( 'fa-lock' => 'lock(protect, admin)' ),
				array( 'fa-flag' => 'flag(report, notification, notify)' ),
				array( 'fa-headphones' => 'headphones(sound, listen, music, audio)' ),
				array( 'fa-volume-off' => 'volume-off(audio, mute, sound, music)' ),
				array( 'fa-volume-down' => 'volume-down(audio, lower, quieter, sound, music)' ),
				array( 'fa-volume-up' => 'volume-up(audio, higher, louder, sound, music)' ),
				array( 'fa-qrcode' => 'qrcode(scan)' ),
				array( 'fa-barcode' => 'barcode(scan)' ),
				array( 'fa-tag' => 'tag(label)' ),
				array( 'fa-tags' => 'tags(labels)' ),
				array( 'fa-book' => 'book(read, documentation)' ),
				array( 'fa-bookmark' => 'bookmark(save)' ),
				array( 'fa-print' => 'print' ),
				array( 'fa-camera' => 'camera(photo, picture, record)' ),
				array( 'fa-video-camera' => 'Video Camera(film, movie, record)' ),
				array( 'fa-picture-o' => 'Picture Outlined(photo, image)' ),
				array( 'fa-pencil' => 'pencil(write, edit, update)' ),
				array( 'fa-map-marker' => 'map-marker(map, pin, location, coordinates, localize, address, travel, where, place)' ),
				array( 'fa-adjust' => 'adjust(contrast)' ),
				array( 'fa-tint' => 'tint(raindrop, waterdrop, drop, droplet)' ),
				array( 'fa-pencil-square-o' => 'Pencil Square Outlined(write, edit, update)(edit)' ),
				array( 'fa-share-square-o' => 'Share Square Outlined(social, send, arrow)' ),
				array( 'fa-check-square-o' => 'Check Square Outlined(todo, done, agree, accept, confirm, ok)' ),
				array( 'fa-arrows' => 'Arrows(move, reorder, resize)' ),
				array( 'fa-plus-circle' => 'Plus Circle(add, new, create, expand)' ),
				array( 'fa-minus-circle' => 'Minus Circle(delete, remove, trash, hide)' ),
				array( 'fa-times-circle' => 'Times Circle(close, exit, x)' ),
				array( 'fa-check-circle' => 'Check Circle(todo, done, agree, accept, confirm, ok)' ),
				array( 'fa-question-circle' => 'Question Circle(help, information, unknown, support)' ),
				array( 'fa-info-circle' => 'Info Circle(help, information, more, details)' ),
				array( 'fa-crosshairs' => 'Crosshairs(picker)' ),
				array( 'fa-times-circle-o' => 'Times Circle Outlined(close, exit, x)' ),
				array( 'fa-check-circle-o' => 'Check Circle Outlined(todo, done, agree, accept, confirm, ok)' ),
				array( 'fa-ban' => 'ban(delete, remove, trash, hide, block, stop, abort, cancel)' ),
				array( 'fa-share' => 'Share(mail-forward)' ),
				array( 'fa-plus' => 'plus(add, new, create, expand)' ),
				array( 'fa-minus' => 'minus(hide, minify, delete, remove, trash, hide, collapse)' ),
				array( 'fa-asterisk' => 'asterisk(details)' ),
				array( 'fa-exclamation-circle' => 'Exclamation Circle(warning, error, problem, notification, alert)' ),
				array( 'fa-gift' => 'gift(present)' ),
				array( 'fa-leaf' => 'leaf(eco, nature, plant)' ),
				array( 'fa-fire' => 'fire(flame, hot, popular)' ),
				array( 'fa-eye' => 'Eye(show, visible, views)' ),
				array( 'fa-eye-slash' => 'Eye Slash(toggle, show, hide, visible, visiblity, views)' ),
				array( 'fa-exclamation-triangle' => 'Exclamation Triangle(warning, error, problem, notification, alert)(warning)' ),
				array( 'fa-plane' => 'plane(travel, trip, location, destination, airplane, fly, mode)' ),
				array( 'fa-calendar' => 'calendar(date, time, when, event)' ),
				array( 'fa-random' => 'random(sort, shuffle)' ),
				array( 'fa-comment' => 'comment(speech, notification, note, chat, bubble, feedback, message, texting, sms)' ),
				array( 'fa-magnet' => 'magnet' ),
				array( 'fa-retweet' => 'retweet(refresh, reload, share)' ),
				array( 'fa-shopping-cart' => 'shopping-cart(checkout, buy, purchase, payment)' ),
				array( 'fa-folder' => 'Folder' ),
				array( 'fa-folder-open' => 'Folder Open' ),
				array( 'fa-arrows-v' => 'Arrows Vertical(resize)' ),
				array( 'fa-arrows-h' => 'Arrows Horizontal(resize)' ),
				array( 'fa-bar-chart' => 'Bar Chart(graph, analytics)(bar-chart-o)' ),
				array( 'fa-camera-retro' => 'camera-retro(photo, picture, record)' ),
				array( 'fa-key' => 'key(unlock, password)' ),
				array( 'fa-cogs' => 'cogs(settings)(gears)' ),
				array( 'fa-comments' => 'comments(conversation, notification, notes, message, texting, sms, chat)' ),
				array( 'fa-thumbs-o-up' => 'Thumbs Up Outlined(like, approve, favorite, agree, hand)' ),
				array( 'fa-thumbs-o-down' => 'Thumbs Down Outlined(dislike, disapprove, disagree, hand)' ),
				array( 'fa-star-half' => 'star-half(award, achievement, rating, score)' ),
				array( 'fa-heart-o' => 'Heart Outlined(love, like, favorite)' ),
				array( 'fa-sign-out' => 'Sign Out(log out, logout, leave, exit, arrow)' ),
				array( 'fa-thumb-tack' => 'Thumb Tack(marker, pin, location, coordinates)' ),
				array( 'fa-external-link' => 'External Link(open, new)' ),
				array( 'fa-sign-in' => 'Sign In(enter, join, log in, login, sign up, sign in, signin, signup, arrow)' ),
				array( 'fa-trophy' => 'trophy(award, achievement, winner, game)' ),
				array( 'fa-upload' => 'Upload(import)' ),
				array( 'fa-lemon-o' => 'Lemon Outlined(food)' ),
				array( 'fa-phone' => 'Phone(call, voice, number, support, earphone)' ),
				array( 'fa-square-o' => 'Square Outlined(block, square, box)' ),
				array( 'fa-bookmark-o' => 'Bookmark Outlined(save)' ),
				array( 'fa-phone-square' => 'Phone Square(call, voice, number, support)' ),
				array( 'fa-unlock' => 'unlock(protect, admin, password, lock)' ),
				array( 'fa-credit-card' => 'credit-card(money, buy, debit, checkout, purchase, payment)' ),
				array( 'fa-rss' => 'rss(blog)(feed)' ),
				array( 'fa-hdd-o' => 'HDD(harddrive, hard drive, storage, save)' ),
				array( 'fa-bullhorn' => 'bullhorn(announcement, share, broadcast, louder)' ),
				array( 'fa-bell' => 'bell(alert, reminder, notification)' ),
				array( 'fa-certificate' => 'certificate(badge, star)' ),
				array( 'fa-globe' => 'Globe(world, planet, map, place, travel, earth, global, translate, all, language, localize, location, coordinates, country)' ),
				array( 'fa-wrench' => 'Wrench(settings, fix, update)' ),
				array( 'fa-tasks' => 'Tasks(progress, loading, downloading, downloads, settings)' ),
				array( 'fa-filter' => 'Filter(funnel, options)' ),
				array( 'fa-briefcase' => 'Briefcase(work, business, office, luggage, bag)' ),
				array( 'fa-users' => 'Users(people, profiles, persons)(group)' ),
				array( 'fa-cloud' => 'Cloud(save)' ),
				array( 'fa-flask' => 'Flask(science, beaker, experimental, labs)' ),
				array( 'fa-square' => 'Square(block, box)' ),
				array( 'fa-bars' => 'Bars(menu, drag, reorder, settings, list, ul, ol, checklist, todo, list, hamburger)(navicon, reorder)' ),
				array( 'fa-magic' => 'magic(wizard, automatic, autocomplete)' ),
				array( 'fa-truck' => 'truck(shipping)' ),
				array( 'fa-money' => 'Money(cash, money, buy, checkout, purchase, payment)' ),
				array( 'fa-sort' => 'Sort(order)(unsorted)' ),
				array( 'fa-sort-desc' => 'Sort Descending(dropdown, more, menu, arrow)(sort-down)' ),
				array( 'fa-sort-asc' => 'Sort Ascending(arrow)(sort-up)' ),
				array( 'fa-envelope' => 'Envelope(email, e-mail, letter, support, mail, notification)' ),
				array( 'fa-gavel' => 'Gavel(legal)' ),
				array( 'fa-tachometer' => 'Tachometer(dashboard)' ),
				array( 'fa-comment-o' => 'comment-o(speech, notification, note, chat, bubble, feedback, message, texting, sms)' ),
				array( 'fa-comments-o' => 'comments-o(conversation, notification, notes, message, texting, sms, chat)' ),
				array( 'fa-bolt' => 'Lightning Bolt(lightning, weather)(flash)' ),
				array( 'fa-sitemap' => 'Sitemap(directory, hierarchy, organization)' ),
				array( 'fa-umbrella' => 'Umbrella' ),
				array( 'fa-lightbulb-o' => 'Lightbulb Outlined(idea, inspiration)' ),
				array( 'fa-exchange' => 'Exchange(transfer, arrows, arrow)' ),
				array( 'fa-cloud-download' => 'Cloud Download(import)' ),
				array( 'fa-cloud-upload' => 'Cloud Upload(import)' ),
				array( 'fa-suitcase' => 'Suitcase(trip, luggage, travel, move, baggage)' ),
				array( 'fa-bell-o' => 'Bell Outlined(alert, reminder, notification)' ),
				array( 'fa-coffee' => 'Coffee(morning, mug, breakfast, tea, drink, cafe)' ),
				array( 'fa-cutlery' => 'Cutlery(food, restaurant, spoon, knife, dinner, eat)' ),
				array( 'fa-building-o' => 'Building Outlined(work, business, apartment, office, company)' ),
				array( 'fa-fighter-jet' => 'fighter-jet(fly, plane, airplane, quick, fast, travel)' ),
				array( 'fa-beer' => 'beer(alcohol, stein, drink, mug, bar, liquor)' ),
				array( 'fa-plus-square' => 'Plus Square(add, new, create, expand)' ),
				array( 'fa-desktop' => 'Desktop(monitor, screen, desktop, computer, demo, device)' ),
				array( 'fa-laptop' => 'Laptop(demo, computer, device)' ),
				array( 'fa-tablet' => 'tablet(ipad, device)' ),
				array( 'fa-mobile' => 'Mobile Phone(cell phone, cellphone, text, call, iphone, number)(mobile-phone)' ),
				array( 'fa-circle-o' => 'Circle Outlined' ),
				array( 'fa-quote-left' => 'quote-left' ),
				array( 'fa-quote-right' => 'quote-right' ),
				array( 'fa-spinner' => 'Spinner(loading, progress)' ),
				array( 'fa-circle' => 'Circle(dot, notification)' ),
				array( 'fa-reply' => 'Reply(mail-reply)' ),
				array( 'fa-folder-o' => 'Folder Outlined' ),
				array( 'fa-folder-open-o' => 'Folder Open Outlined' ),
				array( 'fa-smile-o' => 'Smile Outlined(face, emoticon, happy, approve, satisfied, rating)' ),
				array( 'fa-frown-o' => 'Frown Outlined(face, emoticon, sad, disapprove, rating)' ),
				array( 'fa-meh-o' => 'Meh Outlined(face, emoticon, rating, neutral)' ),
				array( 'fa-gamepad' => 'Gamepad(controller)' ),
				array( 'fa-keyboard-o' => 'Keyboard Outlined(type, input)' ),
				array( 'fa-flag-o' => 'Flag Outlined(report, notification)' ),
				array( 'fa-flag-checkered' => 'flag-checkered(report, notification, notify)' ),
				array( 'fa-terminal' => 'Terminal(command, prompt, code)' ),
				array( 'fa-code' => 'Code(html, brackets)' ),
				array( 'fa-reply-all' => 'reply-all(mail-reply-all)' ),
				array( 'fa-star-half-o' => 'Star Half Outlined(award, achievement, rating, score)(star-half-empty, star-half-full)' ),
				array( 'fa-location-arrow' => 'location-arrow(map, coordinates, location, address, place, where)' ),
				array( 'fa-crop' => 'crop' ),
				array( 'fa-code-fork' => 'code-fork(git, fork, vcs, svn, github, rebase, version, merge)' ),
				array( 'fa-question' => 'Question(help, information, unknown, support)' ),
				array( 'fa-info' => 'Info(help, information, more, details)' ),
				array( 'fa-exclamation' => 'exclamation(warning, error, problem, notification, notify, alert)' ),
				array( 'fa-eraser' => 'eraser(remove, delete)' ),
				array( 'fa-puzzle-piece' => 'Puzzle Piece(addon, add-on, section)' ),
				array( 'fa-microphone' => 'microphone(record, voice, sound)' ),
				array( 'fa-microphone-slash' => 'Microphone Slash(record, voice, sound, mute)' ),
				array( 'fa-shield' => 'shield(award, achievement, winner)' ),
				array( 'fa-calendar-o' => 'calendar-o(date, time, when, event)' ),
				array( 'fa-fire-extinguisher' => 'fire-extinguisher' ),
				array( 'fa-rocket' => 'rocket(app)' ),
				array( 'fa-anchor' => 'Anchor(link)' ),
				array( 'fa-unlock-alt' => 'Unlock Alt(protect, admin, password, lock)' ),
				array( 'fa-bullseye' => 'Bullseye(target)' ),
				array( 'fa-ellipsis-h' => 'Ellipsis Horizontal(dots)' ),
				array( 'fa-ellipsis-v' => 'Ellipsis Vertical(dots)' ),
				array( 'fa-rss-square' => 'RSS Square(feed, blog)' ),
				array( 'fa-ticket' => 'Ticket(movie, pass, support)' ),
				array( 'fa-minus-square' => 'Minus Square(hide, minify, delete, remove, trash, hide, collapse)' ),
				array( 'fa-minus-square-o' => 'Minus Square Outlined(hide, minify, delete, remove, trash, hide, collapse)' ),
				array( 'fa-level-up' => 'Level Up(arrow)' ),
				array( 'fa-level-down' => 'Level Down(arrow)' ),
				array( 'fa-check-square' => 'Check Square(checkmark, done, todo, agree, accept, confirm, ok)' ),
				array( 'fa-pencil-square' => 'Pencil Square(write, edit, update)' ),
				array( 'fa-external-link-square' => 'External Link Square(open, new)' ),
				array( 'fa-share-square' => 'Share Square(social, send)' ),
				array( 'fa-compass' => 'Compass(safari, directory, menu, location)' ),
				array( 'fa-caret-square-o-down' => 'Caret Square Outlined Down(more, dropdown, menu)(toggle-down)' ),
				array( 'fa-caret-square-o-up' => 'Caret Square Outlined Up(toggle-up)' ),
				array( 'fa-caret-square-o-right' => 'Caret Square Outlined Right(next, forward)(toggle-right)' ),
				array( 'fa-sort-alpha-asc' => 'Sort Alpha Ascending' ),
				array( 'fa-sort-alpha-desc' => 'Sort Alpha Descending' ),
				array( 'fa-sort-amount-asc' => 'Sort Amount Ascending' ),
				array( 'fa-sort-amount-desc' => 'Sort Amount Descending' ),
				array( 'fa-sort-numeric-asc' => 'Sort Numeric Ascending(numbers)' ),
				array( 'fa-sort-numeric-desc' => 'Sort Numeric Descending(numbers)' ),
				array( 'fa-thumbs-up' => 'thumbs-up(like, favorite, approve, agree, hand)' ),
				array( 'fa-thumbs-down' => 'thumbs-down(dislike, disapprove, disagree, hand)' ),
				array( 'fa-female' => 'Female(woman, user, person, profile)' ),
				array( 'fa-male' => 'Male(man, user, person, profile)' ),
				array( 'fa-sun-o' => 'Sun Outlined(weather, contrast, lighter, brighten, day)' ),
				array( 'fa-moon-o' => 'Moon Outlined(night, darker, contrast)' ),
				array( 'fa-archive' => 'Archive(box, storage)' ),
				array( 'fa-bug' => 'Bug(report, insect)' ),
				array( 'fa-caret-square-o-left' => 'Caret Square Outlined Left(previous, back)(toggle-left)' ),
				array( 'fa-dot-circle-o' => 'Dot Circle Outlined(target, bullseye, notification)' ),
				array( 'fa-wheelchair' => 'Wheelchair(handicap, person, accessibility, accessibile)' ),
				array( 'fa-plus-square-o' => 'Plus Square Outlined(add, new, create, expand)' ),
				array( 'fa-space-shuttle' => 'Space Shuttle' ),
				array( 'fa-envelope-square' => 'Envelope Square' ),
				array( 'fa-university' => 'University(institution, bank)' ),
				array( 'fa-graduation-cap' => 'Graduation Cap(learning, school, student)(mortar-board)' ),
				array( 'fa-language' => 'Language' ),
				array( 'fa-fax' => 'Fax' ),
				array( 'fa-building' => 'Building(work, business, apartment, office, company)' ),
				array( 'fa-child' => 'Child' ),
				array( 'fa-paw' => 'Paw(pet)' ),
				array( 'fa-spoon' => 'spoon' ),
				array( 'fa-cube' => 'Cube' ),
				array( 'fa-cubes' => 'Cubes' ),
				array( 'fa-recycle' => 'Recycle' ),
				array( 'fa-car' => 'Car(vehicle)(automobile)' ),
				array( 'fa-taxi' => 'Taxi(vehicle)(cab)' ),
				array( 'fa-tree' => 'Tree' ),
				array( 'fa-database' => 'Database' ),
				array( 'fa-file-pdf-o' => 'PDF File Outlined' ),
				array( 'fa-file-word-o' => 'Word File Outlined' ),
				array( 'fa-file-excel-o' => 'Excel File Outlined' ),
				array( 'fa-file-powerpoint-o' => 'Powerpoint File Outlined' ),
				array( 'fa-file-image-o' => 'Image File Outlined(file-photo-o, file-picture-o)' ),
				array( 'fa-file-archive-o' => 'Archive File Outlined(file-zip-o)' ),
				array( 'fa-file-audio-o' => 'Audio File Outlined(file-sound-o)' ),
				array( 'fa-file-video-o' => 'Video File Outlined(file-movie-o)' ),
				array( 'fa-file-code-o' => 'Code File Outlined' ),
				array( 'fa-life-ring' => 'Life Ring(life-bouy, life-buoy, life-saver, support)' ),
				array( 'fa-circle-o-notch' => 'Circle Outlined Notched' ),
				array( 'fa-paper-plane' => 'Paper Plane(send)' ),
				array( 'fa-paper-plane-o' => 'Paper Plane Outlined(send-o)' ),
				array( 'fa-history' => 'History' ),
				array( 'fa-circle-thin' => 'Circle Outlined Thin' ),
				array( 'fa-sliders' => 'Sliders(settings)' ),
				array( 'fa-share-alt' => 'Share Alt' ),
				array( 'fa-share-alt-square' => 'Share Alt Square' ),
				array( 'fa-bomb' => 'Bomb' ),
				array( 'fa-futbol-o' => 'Futbol Outlined(soccer-ball-o)' ),
				array( 'fa-tty' => 'TTY' ),
				array( 'fa-binoculars' => 'Binoculars' ),
				array( 'fa-plug' => 'Plug(power, connect)' ),
				array( 'fa-newspaper-o' => 'Newspaper Outlined(press)' ),
				array( 'fa-wifi' => 'WiFi' ),
				array( 'fa-calculator' => 'Calculator' ),
				array( 'fa-bell-slash' => 'Bell Slash' ),
				array( 'fa-bell-slash-o' => 'Bell Slash Outlined' ),
				array( 'fa-trash' => 'Trash(garbage, delete, remove, hide)' ),
				array( 'fa-copyright' => 'Copyright' ),
				array( 'fa-at' => 'At' ),
				array( 'fa-eyedropper' => 'Eyedropper' ),
				array( 'fa-paint-brush' => 'Paint Brush' ),
				array( 'fa-birthday-cake' => 'Birthday Cake' ),
				array( 'fa-area-chart' => 'Area Chart(graph, analytics)' ),
				array( 'fa-pie-chart' => 'Pie Chart(graph, analytics)' ),
				array( 'fa-line-chart' => 'Line Chart(graph, analytics)' ),
				array( 'fa-toggle-off' => 'Toggle Off' ),
				array( 'fa-toggle-on' => 'Toggle On' ),
				array( 'fa-bicycle' => 'Bicycle(vehicle, bike)' ),
				array( 'fa-bus' => 'Bus(vehicle)' ),
				array( 'fa-cc' => 'Closed Captions' ),
				array( 'fa-cart-plus' => 'Add to Shopping Cart(add, shopping)' ),
				array( 'fa-cart-arrow-down' => 'Shopping Cart Arrow Down(shopping)' ),
				array( 'fa-diamond' => 'Diamond(gem, gemstone)' ),
				array( 'fa-ship' => 'Ship(boat, sea)' ),
				array( 'fa-user-secret' => 'User Secret(whisper, spy, incognito, privacy)' ),
				array( 'fa-motorcycle' => 'Motorcycle(vehicle, bike)' ),
				array( 'fa-street-view' => 'Street View(map)' ),
				array( 'fa-heartbeat' => 'Heartbeat(ekg)' ),
				array( 'fa-server' => 'Server' ),
				array( 'fa-user-plus' => 'Add User(sign up, signup)' ),
				array( 'fa-user-times' => 'Remove User' ),
				array( 'fa-bed' => 'Bed(travel)(hotel)' ),
				array( 'fa-battery-full' => 'Battery Full(power)(battery-4)' ),
				array( 'fa-battery-three-quarters' => 'Battery 3/4 Full(power)(battery-3)' ),
				array( 'fa-battery-half' => 'Battery 1/2 Full(power)(battery-2)' ),
				array( 'fa-battery-quarter' => 'Battery 1/4 Full(power)(battery-1)' ),
				array( 'fa-battery-empty' => 'Battery Empty(power)(battery-0)' ),
				array( 'fa-mouse-pointer' => 'Mouse Pointer' ),
				array( 'fa-i-cursor' => 'I Beam Cursor' ),
				array( 'fa-object-group' => 'Object Group' ),
				array( 'fa-object-ungroup' => 'Object Ungroup' ),
				array( 'fa-sticky-note' => 'Sticky Note' ),
				array( 'fa-sticky-note-o' => 'Sticky Note Outlined' ),
				array( 'fa-clone' => 'Clone(copy)' ),
				array( 'fa-balance-scale' => 'Balance Scale' ),
				array( 'fa-hourglass-o' => 'Hourglass Outlined' ),
				array( 'fa-hourglass-start' => 'Hourglass Start(hourglass-1)' ),
				array( 'fa-hourglass-half' => 'Hourglass Half(hourglass-2)' ),
				array( 'fa-hourglass-end' => 'Hourglass End(hourglass-3)' ),
				array( 'fa-hourglass' => 'Hourglass' ),
				array( 'fa-hand-rock-o' => 'Rock (Hand)(hand-grab-o)' ),
				array( 'fa-hand-paper-o' => 'Paper (Hand)(stop)(hand-stop-o)' ),
				array( 'fa-hand-scissors-o' => 'Scissors (Hand)' ),
				array( 'fa-hand-lizard-o' => 'Lizard (Hand)' ),
				array( 'fa-hand-spock-o' => 'Spock (Hand)' ),
				array( 'fa-hand-pointer-o' => 'Hand Pointer' ),
				array( 'fa-hand-peace-o' => 'Hand Peace' ),
				array( 'fa-trademark' => 'Trademark' ),
				array( 'fa-registered' => 'Registered Trademark' ),
				array( 'fa-creative-commons' => 'Creative Commons' ),
				array( 'fa-television' => 'Television(display, computer, monitor)(tv)' ),
				array( 'fa-calendar-plus-o' => 'Calendar Plus Outlined' ),
				array( 'fa-calendar-minus-o' => 'Calendar Minus Outlined' ),
				array( 'fa-calendar-times-o' => 'Calendar Times Outlined' ),
				array( 'fa-calendar-check-o' => 'Calendar Check Outlined(ok)' ),
				array( 'fa-industry' => 'Industry(factory)' ),
				array( 'fa-map-pin' => 'Map Pin' ),
				array( 'fa-map-signs' => 'Map Signs' ),
				array( 'fa-map-o' => 'Map Outline' ),
				array( 'fa-map' => 'Map' ),
				array( 'fa-commenting' => 'Commenting(message)' ),
				array( 'fa-commenting-o' => 'Commenting Outlined(message)' ),
				array( 'fa-credit-card-alt' => 'Credit Card(money, buy, debit, checkout, purchase, payment, credit card)' ),
				array( 'fa-shopping-bag' => 'Shopping Bag' ),
				array( 'fa-shopping-basket' => 'Shopping Basket' ),
				array( 'fa-hashtag' => 'Hashtag' ),
				array( 'fa-bluetooth' => 'Bluetooth' ),
				array( 'fa-bluetooth-b' => 'Bluetooth' ),
				array( 'fa-percent' => 'Percent' ),
				array( 'fa-universal-access' => 'Universal Access' ),
				array( 'fa-wheelchair-alt' => 'Wheelchair Alt' ),
				array( 'fa-question-circle-o' => 'Question Circle Outlined' ),
				array( 'fa-blind' => 'Blind' ),
				array( 'fa-audio-description' => 'Audio Description' ),
				array( 'fa-volume-control-phone' => 'Volume Control Phone' ),
				array( 'fa-braille' => 'Braille' ),
				array( 'fa-assistive-listening-systems' => 'Assistive Listening Systems' ),
				array( 'fa-american-sign-language-interpreting' => 'American Sign Language Interpreting(asl-interpreting)' ),
				array( 'fa-deaf' => 'Deaf(deafness, hard-of-hearing)' ),
				array( 'fa-sign-language' => 'Sign Language(signing)' ),
				array( 'fa-low-vision' => 'Low Vision' ),
			),
			'Medical Icons'         => array(
				array( 'fa-heart' => 'Heart(love, like, favorite)' ),
				array( 'fa-heart-o' => 'Heart Outlined(love, like, favorite)' ),
				array( 'fa-user-md' => 'user-md(doctor, profile, medical, nurse)' ),
				array( 'fa-stethoscope' => 'Stethoscope' ),
				array( 'fa-hospital-o' => 'hospital Outlined(building)' ),
				array( 'fa-ambulance' => 'ambulance(vehicle, support, help)' ),
				array( 'fa-medkit' => 'medkit(first aid, firstaid, help, support, health)' ),
				array( 'fa-h-square' => 'H Square(hospital, hotel)' ),
				array( 'fa-plus-square' => 'Plus Square(add, new, create, expand)' ),
				array( 'fa-wheelchair' => 'Wheelchair(handicap, person, accessibility, accessibile)' ),
				array( 'fa-heartbeat' => 'Heartbeat(ekg)' ),
			),
			'Text Editor Icons'     => array(
				array( 'fa-th-large' => 'th-large(blocks, squares, boxes, grid)' ),
				array( 'fa-th' => 'th(blocks, squares, boxes, grid)' ),
				array( 'fa-th-list' => 'th-list(ul, ol, checklist, finished, completed, done, todo)' ),
				array( 'fa-file-o' => 'File Outlined(new, page, pdf, document)' ),
				array( 'fa-repeat' => 'Repeat(redo, forward)(rotate-right)' ),
				array( 'fa-list-alt' => 'list-alt(ul, ol, checklist, finished, completed, done, todo)' ),
				array( 'fa-font' => 'font(text)' ),
				array( 'fa-bold' => 'bold' ),
				array( 'fa-italic' => 'italic(italics)' ),
				array( 'fa-text-height' => 'text-height' ),
				array( 'fa-text-width' => 'text-width' ),
				array( 'fa-align-left' => 'align-left(text)' ),
				array( 'fa-align-center' => 'align-center(middle, text)' ),
				array( 'fa-align-right' => 'align-right(text)' ),
				array( 'fa-align-justify' => 'align-justify(text)' ),
				array( 'fa-list' => 'list(ul, ol, checklist, finished, completed, done, todo)' ),
				array( 'fa-outdent' => 'Outdent(dedent)' ),
				array( 'fa-indent' => 'Indent' ),
				array( 'fa-link' => 'Link(chain)(chain)' ),
				array( 'fa-scissors' => 'Scissors(cut)' ),
				array( 'fa-files-o' => 'Files Outlined(duplicate, clone, copy)(copy)' ),
				array( 'fa-paperclip' => 'Paperclip(attachment)' ),
				array( 'fa-floppy-o' => 'Floppy Outlined(save)' ),
				array( 'fa-list-ul' => 'list-ul(ul, ol, checklist, todo, list)' ),
				array( 'fa-list-ol' => 'list-ol(ul, ol, checklist, list, todo, list, numbers)' ),
				array( 'fa-strikethrough' => 'Strikethrough' ),
				array( 'fa-underline' => 'Underline' ),
				array( 'fa-table' => 'table(data, excel, spreadsheet)' ),
				array( 'fa-columns' => 'Columns(split, panes)' ),
				array( 'fa-undo' => 'Undo(back)(rotate-left)' ),
				array( 'fa-clipboard' => 'Clipboard(copy)(paste)' ),
				array( 'fa-file-text-o' => 'File Text Outlined(new, page, pdf, document)' ),
				array( 'fa-chain-broken' => 'Chain Broken(remove)(unlink)' ),
				array( 'fa-superscript' => 'superscript(exponential)' ),
				array( 'fa-subscript' => 'subscript' ),
				array( 'fa-eraser' => 'eraser(remove, delete)' ),
				array( 'fa-file' => 'File(new, page, pdf, document)' ),
				array( 'fa-file-text' => 'File Text(new, page, pdf, document)' ),
				array( 'fa-header' => 'header(heading)' ),
				array( 'fa-paragraph' => 'paragraph' ),
			),
			'Spinner Icons'         => array(
				array( 'fa-cog' => 'cog(settings)(gear)' ),
				array( 'fa-refresh' => 'refresh(reload, sync)' ),
				array( 'fa-spinner' => 'Spinner(loading, progress)' ),
				array( 'fa-circle-o-notch' => 'Circle Outlined Notched' ),
			),
			'File Type Icons'       => array(
				array( 'fa-file-o' => 'File Outlined(new, page, pdf, document)' ),
				array( 'fa-file-text-o' => 'File Text Outlined(new, page, pdf, document)' ),
				array( 'fa-file' => 'File(new, page, pdf, document)' ),
				array( 'fa-file-text' => 'File Text(new, page, pdf, document)' ),
				array( 'fa-file-pdf-o' => 'PDF File Outlined' ),
				array( 'fa-file-word-o' => 'Word File Outlined' ),
				array( 'fa-file-excel-o' => 'Excel File Outlined' ),
				array( 'fa-file-powerpoint-o' => 'Powerpoint File Outlined' ),
				array( 'fa-file-image-o' => 'Image File Outlined(file-photo-o, file-picture-o)' ),
				array( 'fa-file-archive-o' => 'Archive File Outlined(file-zip-o)' ),
				array( 'fa-file-audio-o' => 'Audio File Outlined(file-sound-o)' ),
				array( 'fa-file-video-o' => 'Video File Outlined(file-movie-o)' ),
				array( 'fa-file-code-o' => 'Code File Outlined' ),
			),
			'Directional Icons'     => array(
				array( 'fa-arrow-circle-o-down' => 'Arrow Circle Outlined Down(download)' ),
				array( 'fa-arrow-circle-o-up' => 'Arrow Circle Outlined Up' ),
				array( 'fa-arrows' => 'Arrows(move, reorder, resize)' ),
				array( 'fa-chevron-left' => 'chevron-left(bracket, previous, back)' ),
				array( 'fa-chevron-right' => 'chevron-right(bracket, next, forward)' ),
				array( 'fa-arrow-left' => 'arrow-left(previous, back)' ),
				array( 'fa-arrow-right' => 'arrow-right(next, forward)' ),
				array( 'fa-arrow-up' => 'arrow-up' ),
				array( 'fa-arrow-down' => 'arrow-down(download)' ),
				array( 'fa-chevron-up' => 'chevron-up' ),
				array( 'fa-chevron-down' => 'chevron-down' ),
				array( 'fa-arrows-v' => 'Arrows Vertical(resize)' ),
				array( 'fa-arrows-h' => 'Arrows Horizontal(resize)' ),
				array( 'fa-hand-o-right' => 'Hand Outlined Right(point, right, next, forward, finger)' ),
				array( 'fa-hand-o-left' => 'Hand Outlined Left(point, left, previous, back, finger)' ),
				array( 'fa-hand-o-up' => 'Hand Outlined Up(point, finger)' ),
				array( 'fa-hand-o-down' => 'Hand Outlined Down(point, finger)' ),
				array( 'fa-arrow-circle-left' => 'Arrow Circle Left(previous, back)' ),
				array( 'fa-arrow-circle-right' => 'Arrow Circle Right(next, forward)' ),
				array( 'fa-arrow-circle-up' => 'Arrow Circle Up' ),
				array( 'fa-arrow-circle-down' => 'Arrow Circle Down(download)' ),
				array( 'fa-arrows-alt' => 'Arrows Alt(expand, enlarge, fullscreen, bigger, move, reorder, resize, arrow)' ),
				array( 'fa-caret-down' => 'Caret Down(more, dropdown, menu, triangle down, arrow)' ),
				array( 'fa-caret-up' => 'Caret Up(triangle up, arrow)' ),
				array( 'fa-caret-left' => 'Caret Left(previous, back, triangle left, arrow)' ),
				array( 'fa-caret-right' => 'Caret Right(next, forward, triangle right, arrow)' ),
				array( 'fa-exchange' => 'Exchange(transfer, arrows, arrow)' ),
				array( 'fa-angle-double-left' => 'Angle Double Left(laquo, quote, previous, back, arrows)' ),
				array( 'fa-angle-double-right' => 'Angle Double Right(raquo, quote, next, forward, arrows)' ),
				array( 'fa-angle-double-up' => 'Angle Double Up(arrows)' ),
				array( 'fa-angle-double-down' => 'Angle Double Down(arrows)' ),
				array( 'fa-angle-left' => 'angle-left(previous, back, arrow)' ),
				array( 'fa-angle-right' => 'angle-right(next, forward, arrow)' ),
				array( 'fa-angle-up' => 'angle-up(arrow)' ),
				array( 'fa-angle-down' => 'angle-down(arrow)' ),
				array( 'fa-chevron-circle-left' => 'Chevron Circle Left(previous, back, arrow)' ),
				array( 'fa-chevron-circle-right' => 'Chevron Circle Right(next, forward, arrow)' ),
				array( 'fa-chevron-circle-up' => 'Chevron Circle Up(arrow)' ),
				array( 'fa-chevron-circle-down' => 'Chevron Circle Down(more, dropdown, menu, arrow)' ),
				array( 'fa-caret-square-o-down' => 'Caret Square Outlined Down(more, dropdown, menu)(toggle-down)' ),
				array( 'fa-caret-square-o-up' => 'Caret Square Outlined Up(toggle-up)' ),
				array( 'fa-caret-square-o-right' => 'Caret Square Outlined Right(next, forward)(toggle-right)' ),
				array( 'fa-long-arrow-down' => 'Long Arrow Down' ),
				array( 'fa-long-arrow-up' => 'Long Arrow Up' ),
				array( 'fa-long-arrow-left' => 'Long Arrow Left(previous, back)' ),
				array( 'fa-long-arrow-right' => 'Long Arrow Right' ),
				array( 'fa-arrow-circle-o-right' => 'Arrow Circle Outlined Right(next, forward)' ),
				array( 'fa-arrow-circle-o-left' => 'Arrow Circle Outlined Left(previous, back)' ),
				array( 'fa-caret-square-o-left' => 'Caret Square Outlined Left(previous, back)(toggle-left)' ),
			),
			'Video Player Icons'    => array(
				array( 'fa-play-circle-o' => 'Play Circle Outlined' ),
				array( 'fa-step-backward' => 'step-backward(rewind, previous, beginning, start, first)' ),
				array( 'fa-fast-backward' => 'fast-backward(rewind, previous, beginning, start, first)' ),
				array( 'fa-backward' => 'backward(rewind, previous)' ),
				array( 'fa-play' => 'play(start, playing, music, sound)' ),
				array( 'fa-pause' => 'pause(wait)' ),
				array( 'fa-stop' => 'stop(block, box, square)' ),
				array( 'fa-forward' => 'forward(forward, next)' ),
				array( 'fa-fast-forward' => 'fast-forward(next, end, last)' ),
				array( 'fa-step-forward' => 'step-forward(next, end, last)' ),
				array( 'fa-eject' => 'eject' ),
				array( 'fa-expand' => 'Expand(enlarge, bigger, resize)' ),
				array( 'fa-compress' => 'Compress(collapse, combine, contract, merge, smaller)' ),
				array( 'fa-random' => 'random(sort, shuffle)' ),
				array( 'fa-arrows-alt' => 'Arrows Alt(expand, enlarge, fullscreen, bigger, move, reorder, resize, arrow)' ),
				array( 'fa-play-circle' => 'Play Circle(start, playing)' ),
				array( 'fa-youtube-play' => 'YouTube Play(start, playing)' ),
				array( 'fa-pause-circle' => 'Pause Circle' ),
				array( 'fa-pause-circle-o' => 'Pause Circle Outlined' ),
				array( 'fa-stop-circle' => 'Stop Circle' ),
				array( 'fa-stop-circle-o' => 'Stop Circle Outlined' ),
			),
			'Form Control Icons'    => array(
				array( 'fa-check-square-o' => 'Check Square Outlined(todo, done, agree, accept, confirm, ok)' ),
				array( 'fa-square-o' => 'Square Outlined(block, square, box)' ),
				array( 'fa-square' => 'Square(block, box)' ),
				array( 'fa-plus-square' => 'Plus Square(add, new, create, expand)' ),
				array( 'fa-circle-o' => 'Circle Outlined' ),
				array( 'fa-circle' => 'Circle(dot, notification)' ),
				array( 'fa-minus-square' => 'Minus Square(hide, minify, delete, remove, trash, hide, collapse)' ),
				array( 'fa-minus-square-o' => 'Minus Square Outlined(hide, minify, delete, remove, trash, hide, collapse)' ),
				array( 'fa-check-square' => 'Check Square(checkmark, done, todo, agree, accept, confirm, ok)' ),
				array( 'fa-dot-circle-o' => 'Dot Circle Outlined(target, bullseye, notification)' ),
				array( 'fa-plus-square-o' => 'Plus Square Outlined(add, new, create, expand)' ),
			),
			'Transportation Icons'  => array(
				array( 'fa-plane' => 'plane(travel, trip, location, destination, airplane, fly, mode)' ),
				array( 'fa-truck' => 'truck(shipping)' ),
				array( 'fa-ambulance' => 'ambulance(vehicle, support, help)' ),
				array( 'fa-fighter-jet' => 'fighter-jet(fly, plane, airplane, quick, fast, travel)' ),
				array( 'fa-rocket' => 'rocket(app)' ),
				array( 'fa-wheelchair' => 'Wheelchair(handicap, person, accessibility, accessibile)' ),
				array( 'fa-space-shuttle' => 'Space Shuttle' ),
				array( 'fa-car' => 'Car(vehicle)(automobile)' ),
				array( 'fa-taxi' => 'Taxi(vehicle)(cab)' ),
				array( 'fa-bicycle' => 'Bicycle(vehicle, bike)' ),
				array( 'fa-bus' => 'Bus(vehicle)' ),
				array( 'fa-ship' => 'Ship(boat, sea)' ),
				array( 'fa-motorcycle' => 'Motorcycle(vehicle, bike)' ),
				array( 'fa-train' => 'Train' ),
				array( 'fa-subway' => 'Subway' ),
			),
			'Chart Icons'           => array(
				array( 'fa-bar-chart' => 'Bar Chart(graph, analytics)(bar-chart-o)' ),
				array( 'fa-area-chart' => 'Area Chart(graph, analytics)' ),
				array( 'fa-pie-chart' => 'Pie Chart(graph, analytics)' ),
				array( 'fa-line-chart' => 'Line Chart(graph, analytics)' ),
			),
			'Brand Icons'           => array(
				array( 'fa-twitter-square' => 'Twitter Square(tweet, social network)' ),
				array( 'fa-facebook-square' => 'Facebook Square(social network)' ),
				array( 'fa-linkedin-square' => 'LinkedIn Square' ),
				array( 'fa-github-square' => 'GitHub Square(octocat)' ),
				array( 'fa-twitter' => 'Twitter(tweet, social network)' ),
				array( 'fa-facebook' => 'Facebook(social network)(facebook-f)' ),
				array( 'fa-github' => 'GitHub(octocat)' ),
				array( 'fa-pinterest' => 'Pinterest' ),
				array( 'fa-pinterest-square' => 'Pinterest Square' ),
				array( 'fa-google-plus-square' => 'Google Plus Square(social network)' ),
				array( 'fa-google-plus' => 'Google Plus(social network)' ),
				array( 'fa-linkedin' => 'LinkedIn' ),
				array( 'fa-github-alt' => 'GitHub Alt(octocat)' ),
				array( 'fa-maxcdn' => 'MaxCDN' ),
				array( 'fa-html5' => 'HTML 5 Logo' ),
				array( 'fa-css3' => 'CSS 3 Logo(code)' ),
				array( 'fa-btc' => 'Bitcoin (BTC)(bitcoin)' ),
				array( 'fa-youtube-square' => 'YouTube Square(video, film)' ),
				array( 'fa-youtube' => 'YouTube(video, film)' ),
				array( 'fa-xing' => 'Xing' ),
				array( 'fa-xing-square' => 'Xing Square' ),
				array( 'fa-youtube-play' => 'YouTube Play(start, playing)' ),
				array( 'fa-dropbox' => 'Dropbox' ),
				array( 'fa-stack-overflow' => 'Stack Overflow' ),
				array( 'fa-instagram' => 'Instagram' ),
				array( 'fa-flickr' => 'Flickr' ),
				array( 'fa-adn' => 'App.net' ),
				array( 'fa-bitbucket' => 'Bitbucket(git)' ),
				array( 'fa-bitbucket-square' => 'Bitbucket Square(git)' ),
				array( 'fa-tumblr' => 'Tumblr' ),
				array( 'fa-tumblr-square' => 'Tumblr Square' ),
				array( 'fa-apple' => 'Apple(osx, food)' ),
				array( 'fa-windows' => 'Windows(microsoft)' ),
				array( 'fa-android' => 'Android(robot)' ),
				array( 'fa-linux' => 'Linux(tux)' ),
				array( 'fa-dribbble' => 'Dribbble' ),
				array( 'fa-skype' => 'Skype' ),
				array( 'fa-foursquare' => 'Foursquare' ),
				array( 'fa-trello' => 'Trello' ),
				array( 'fa-gratipay' => 'Gratipay (Gittip)(heart, like, favorite, love)(gittip)' ),
				array( 'fa-vk' => 'VK' ),
				array( 'fa-weibo' => 'Weibo' ),
				array( 'fa-renren' => 'Renren' ),
				array( 'fa-pagelines' => 'Pagelines(leaf, leaves, tree, plant, eco, nature)' ),
				array( 'fa-stack-exchange' => 'Stack Exchange' ),
				array( 'fa-vimeo-square' => 'Vimeo Square' ),
				array( 'fa-slack' => 'Slack Logo(hashtag, anchor, hash)' ),
				array( 'fa-wordpress' => 'WordPress Logo' ),
				array( 'fa-openid' => 'OpenID' ),
				array( 'fa-yahoo' => 'Yahoo Logo' ),
				array( 'fa-google' => 'Google Logo' ),
				array( 'fa-reddit' => 'reddit Logo' ),
				array( 'fa-reddit-square' => 'reddit Square' ),
				array( 'fa-stumbleupon-circle' => 'StumbleUpon Circle' ),
				array( 'fa-stumbleupon' => 'StumbleUpon Logo' ),
				array( 'fa-delicious' => 'Delicious Logo' ),
				array( 'fa-digg' => 'Digg Logo' ),
				array( 'fa-pied-piper-pp' => 'Pied Piper PP Logo (Old)' ),
				array( 'fa-pied-piper-alt' => 'Pied Piper Alternate Logo' ),
				array( 'fa-drupal' => 'Drupal Logo' ),
				array( 'fa-joomla' => 'Joomla Logo' ),
				array( 'fa-behance' => 'Behance' ),
				array( 'fa-behance-square' => 'Behance Square' ),
				array( 'fa-steam' => 'Steam' ),
				array( 'fa-steam-square' => 'Steam Square' ),
				array( 'fa-spotify' => 'Spotify' ),
				array( 'fa-deviantart' => 'deviantART' ),
				array( 'fa-soundcloud' => 'SoundCloud' ),
				array( 'fa-vine' => 'Vine' ),
				array( 'fa-codepen' => 'Codepen' ),
				array( 'fa-jsfiddle' => 'jsFiddle' ),
				array( 'fa-rebel' => 'Rebel Alliance(ra, resistance)' ),
				array( 'fa-empire' => 'Galactic Empire(ge)' ),
				array( 'fa-git-square' => 'Git Square' ),
				array( 'fa-git' => 'Git' ),
				array( 'fa-hacker-news' => 'Hacker News(y-combinator-square, yc-square)' ),
				array( 'fa-tencent-weibo' => 'Tencent Weibo' ),
				array( 'fa-qq' => 'QQ' ),
				array( 'fa-weixin' => 'Weixin (WeChat)(wechat)' ),
				array( 'fa-share-alt' => 'Share Alt' ),
				array( 'fa-share-alt-square' => 'Share Alt Square' ),
				array( 'fa-slideshare' => 'Slideshare' ),
				array( 'fa-twitch' => 'Twitch' ),
				array( 'fa-yelp' => 'Yelp' ),
				array( 'fa-paypal' => 'Paypal' ),
				array( 'fa-google-wallet' => 'Google Wallet' ),
				array( 'fa-cc-visa' => 'Visa Credit Card' ),
				array( 'fa-cc-mastercard' => 'MasterCard Credit Card' ),
				array( 'fa-cc-discover' => 'Discover Credit Card' ),
				array( 'fa-cc-amex' => 'American Express Credit Card(amex)' ),
				array( 'fa-cc-paypal' => 'Paypal Credit Card' ),
				array( 'fa-cc-stripe' => 'Stripe Credit Card' ),
				array( 'fa-lastfm' => 'last.fm' ),
				array( 'fa-lastfm-square' => 'last.fm Square' ),
				array( 'fa-ioxhost' => 'ioxhost' ),
				array( 'fa-angellist' => 'AngelList' ),
				array( 'fa-meanpath' => 'meanpath' ),
				array( 'fa-buysellads' => 'BuySellAds' ),
				array( 'fa-connectdevelop' => 'Connect Develop' ),
				array( 'fa-dashcube' => 'DashCube' ),
				array( 'fa-forumbee' => 'Forumbee' ),
				array( 'fa-leanpub' => 'Leanpub' ),
				array( 'fa-sellsy' => 'Sellsy' ),
				array( 'fa-shirtsinbulk' => 'Shirts in Bulk' ),
				array( 'fa-simplybuilt' => 'SimplyBuilt' ),
				array( 'fa-skyatlas' => 'skyatlas' ),
				array( 'fa-facebook-official' => 'Facebook Official' ),
				array( 'fa-pinterest-p' => 'Pinterest P' ),
				array( 'fa-whatsapp' => 'What\'s App' ),
				array( 'fa-viacoin' => 'Viacoin' ),
				array( 'fa-medium' => 'Medium' ),
				array( 'fa-y-combinator' => 'Y Combinator(yc)' ),
				array( 'fa-optin-monster' => 'Optin Monster' ),
				array( 'fa-opencart' => 'OpenCart' ),
				array( 'fa-expeditedssl' => 'ExpeditedSSL' ),
				array( 'fa-cc-jcb' => 'JCB Credit Card' ),
				array( 'fa-cc-diners-club' => 'Diner\'s Club Credit Card' ),
				array( 'fa-gg' => 'GG Currency' ),
				array( 'fa-gg-circle' => 'GG Currency Circle' ),
				array( 'fa-tripadvisor' => 'TripAdvisor' ),
				array( 'fa-odnoklassniki' => 'Odnoklassniki' ),
				array( 'fa-odnoklassniki-square' => 'Odnoklassniki Square' ),
				array( 'fa-get-pocket' => 'Get Pocket' ),
				array( 'fa-wikipedia-w' => 'Wikipedia W' ),
				array( 'fa-safari' => 'Safari(browser)' ),
				array( 'fa-chrome' => 'Chrome(browser)' ),
				array( 'fa-firefox' => 'Firefox(browser)' ),
				array( 'fa-opera' => 'Opera' ),
				array( 'fa-internet-explorer' => 'Internet-explorer(browser, ie)' ),
				array( 'fa-contao' => 'Contao' ),
				array( 'fa-500px' => '500px' ),
				array( 'fa-amazon' => 'Amazon' ),
				array( 'fa-houzz' => 'Houzz' ),
				array( 'fa-vimeo' => 'Vimeo' ),
				array( 'fa-black-tie' => 'Font Awesome Black Tie' ),
				array( 'fa-fonticons' => 'Fonticons' ),
				array( 'fa-reddit-alien' => 'reddit Alien' ),
				array( 'fa-edge' => 'Edge Browser(browser, ie)' ),
				array( 'fa-codiepie' => 'Codie Pie' ),
				array( 'fa-modx' => 'MODX' ),
				array( 'fa-fort-awesome' => 'Fort Awesome' ),
				array( 'fa-usb' => 'USB' ),
				array( 'fa-product-hunt' => 'Product Hunt' ),
				array( 'fa-mixcloud' => 'Mixcloud' ),
				array( 'fa-scribd' => 'Scribd' ),
				array( 'fa-bluetooth' => 'Bluetooth' ),
				array( 'fa-bluetooth-b' => 'Bluetooth' ),
				array( 'fa-gitlab' => 'GitLab' ),
				array( 'fa-wpbeginner' => 'WPBeginner' ),
				array( 'fa-wpforms' => 'WPForms' ),
				array( 'fa-envira' => 'Envira Gallery(leaf)' ),
				array( 'fa-glide' => 'Glide' ),
				array( 'fa-glide-g' => 'Glide G' ),
				array( 'fa-viadeo' => 'Viadeo' ),
				array( 'fa-viadeo-square' => 'Viadeo Square' ),
				array( 'fa-snapchat' => 'Snapchat' ),
				array( 'fa-snapchat-ghost' => 'Snapchat Ghost' ),
				array( 'fa-snapchat-square' => 'Snapchat Square' ),
				array( 'fa-pied-piper' => 'Pied Piper Logo' ),
				array( 'fa-first-order' => 'First Order' ),
				array( 'fa-yoast' => 'Yoast' ),
				array( 'fa-themeisle' => 'ThemeIsle' ),
				array( 'fa-google-plus-official' => 'Google Plus Official(google-plus-circle)' ),
				array( 'fa-font-awesome' => 'Font Awesome(fa)' ),
			),
			'Hand Icons'            => array(
				array( 'fa-thumbs-o-up' => 'Thumbs Up Outlined(like, approve, favorite, agree, hand)' ),
				array( 'fa-thumbs-o-down' => 'Thumbs Down Outlined(dislike, disapprove, disagree, hand)' ),
				array( 'fa-hand-o-right' => 'Hand Outlined Right(point, right, next, forward, finger)' ),
				array( 'fa-hand-o-left' => 'Hand Outlined Left(point, left, previous, back, finger)' ),
				array( 'fa-hand-o-up' => 'Hand Outlined Up(point, finger)' ),
				array( 'fa-hand-o-down' => 'Hand Outlined Down(point, finger)' ),
				array( 'fa-thumbs-up' => 'thumbs-up(like, favorite, approve, agree, hand)' ),
				array( 'fa-thumbs-down' => 'thumbs-down(dislike, disapprove, disagree, hand)' ),
				array( 'fa-hand-rock-o' => 'Rock (Hand)(hand-grab-o)' ),
				array( 'fa-hand-paper-o' => 'Paper (Hand)(stop)(hand-stop-o)' ),
				array( 'fa-hand-scissors-o' => 'Scissors (Hand)' ),
				array( 'fa-hand-lizard-o' => 'Lizard (Hand)' ),
				array( 'fa-hand-spock-o' => 'Spock (Hand)' ),
				array( 'fa-hand-pointer-o' => 'Hand Pointer' ),
				array( 'fa-hand-peace-o' => 'Hand Peace' ),
			),
			'Payment Icons'         => array(
				array( 'fa-credit-card' => 'credit-card(money, buy, debit, checkout, purchase, payment)' ),
				array( 'fa-paypal' => 'Paypal' ),
				array( 'fa-google-wallet' => 'Google Wallet' ),
				array( 'fa-cc-visa' => 'Visa Credit Card' ),
				array( 'fa-cc-mastercard' => 'MasterCard Credit Card' ),
				array( 'fa-cc-discover' => 'Discover Credit Card' ),
				array( 'fa-cc-amex' => 'American Express Credit Card(amex)' ),
				array( 'fa-cc-paypal' => 'Paypal Credit Card' ),
				array( 'fa-cc-stripe' => 'Stripe Credit Card' ),
				array( 'fa-cc-jcb' => 'JCB Credit Card' ),
				array( 'fa-cc-diners-club' => 'Diner\'s Club Credit Card' ),
				array( 'fa-credit-card-alt' => 'Credit Card(money, buy, debit, checkout, purchase, payment, credit card)' ),
			),
			'Currency Icons'        => array(
				array( 'fa-money' => 'Money(cash, money, buy, checkout, purchase, payment)' ),
				array( 'fa-eur' => 'Euro (EUR)(euro)' ),
				array( 'fa-gbp' => 'GBP' ),
				array( 'fa-usd' => 'US Dollar(dollar)' ),
				array( 'fa-inr' => 'Indian Rupee (INR)(rupee)' ),
				array( 'fa-jpy' => 'Japanese Yen (JPY)(cny, rmb, yen)' ),
				array( 'fa-rub' => 'Russian Ruble (RUB)(ruble, rouble)' ),
				array( 'fa-krw' => 'Korean Won (KRW)(won)' ),
				array( 'fa-btc' => 'Bitcoin (BTC)(bitcoin)' ),
				array( 'fa-try' => 'Turkish Lira (TRY)(turkish-lira)' ),
				array( 'fa-ils' => 'Shekel (ILS)(shekel, sheqel)' ),
				array( 'fa-gg' => 'GG Currency' ),
				array( 'fa-gg-circle' => 'GG Currency Circle' ),
			),
			'Accessibility Icons'   => array(
				array( 'fa-wheelchair' => 'Wheelchair(handicap, person, accessibility, accessibile)' ),
				array( 'fa-tty' => 'TTY' ),
				array( 'fa-cc' => 'Closed Captions' ),
				array( 'fa-universal-access' => 'Universal Access' ),
				array( 'fa-wheelchair-alt' => 'Wheelchair Alt' ),
				array( 'fa-question-circle-o' => 'Question Circle Outlined' ),
				array( 'fa-blind' => 'Blind' ),
				array( 'fa-audio-description' => 'Audio Description' ),
				array( 'fa-volume-control-phone' => 'Volume Control Phone' ),
				array( 'fa-braille' => 'Braille' ),
				array( 'fa-assistive-listening-systems' => 'Assistive Listening Systems' ),
				array( 'fa-american-sign-language-interpreting' => 'American Sign Language Interpreting(asl-interpreting)' ),
				array( 'fa-deaf' => 'Deaf(deafness, hard-of-hearing)' ),
				array( 'fa-sign-language' => 'Sign Language(signing)' ),
				array( 'fa-low-vision' => 'Low Vision' ),
			),
			'Gender Icons'          => array(
				array( 'fa-venus' => 'Venus(female)' ),
				array( 'fa-mars' => 'Mars(male)' ),
				array( 'fa-mercury' => 'Mercury(transgender)' ),
				array( 'fa-transgender' => 'Transgender(intersex)' ),
				array( 'fa-transgender-alt' => 'Transgender Alt' ),
				array( 'fa-venus-double' => 'Venus Double' ),
				array( 'fa-mars-double' => 'Mars Double' ),
				array( 'fa-venus-mars' => 'Venus Mars' ),
				array( 'fa-mars-stroke' => 'Mars Stroke' ),
				array( 'fa-mars-stroke-v' => 'Mars Stroke Vertical' ),
				array( 'fa-mars-stroke-h' => 'Mars Stroke Horizontal' ),
				array( 'fa-neuter' => 'Neuter' ),
				array( 'fa-genderless' => 'Genderless' ),
			),
		);

		return $fontawesome_icons;
	}
endif;
